log:
  level: DEBUG
  filePath: "/home/gptops/traefik/logs/traefik.log"

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true

providers:
  file:
    directory: "/home/gptops/traefik/config"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: jlm501mailme@gmail.com
      storage: /home/gptops/traefik/acme.json
      httpChallenge:
        entryPoint: web
